

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST"
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS"
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL"
export const   PATIENT_REGISTER_RESET = "PATIENT_REGISTER_RESET" 


export const TRIAGE_VISIT_REQUEST = "TRIAGE_VISIT_REQUEST"
export const  TRIAGE_VISIT_SUCCESS = "TRIAGE_VISIT_SUCCESS"
export const  TRIAGE_VISIT_FAIL = "TRIAGE_VISIT_FAIL"
export const TRIAGE_VISIT_RESET = "TRIAGE_VISIT_RESET"


export const TRIAGE_VISIT_LIST_REQUEST = "TRIAGE_VISIT_LIST_REQUEST"
export const TRIAGE_VISIT_LIST_SUCCESS = "TRIAGE_VISIT_LIST_SUCCESS"
export const TRIAGE_VISIT_LIST_FAIL = "TRIAGE_VISIT_LIST_FAIL"
export const TRIAGE_VISIT_LIST_RESET = "TRIAGE_VISIT_LIST_RESET"

export const POST_PATIENT_VITALS_REQUEST = "POST_PATIENT_VITALS_REQUEST"
export const POST_PATIENT_VITALS_SUCCESS = "POST_PATIENT_VITALS_SUCCESS"
export const POST_PATIENT_VITALS_FAIL = "POST_PATIENT_VITALS_FAIL"
export const POST_PATIENT_VITALS_RESET = "POST_PATIENT_VITALS_RESET"

export const POST_DOCTOR_TREATMENT_REQUEST = "POST_DOCTOR_TREATMENT_REQUEST"
export const POST_DOCTOR_TREATMENT_SUCCESS = "POST_DOCTOR_TREATMENT_SUCCESS"
export const POST_DOCTOR_TREATMENT_FAIL = "POST_DOCTOR_TREATMENT_FAIL"
export const POST_DOCTOR_TREATMENT_RESET = "POST_DOCTOR_TREATMENT_RESET"


export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST"
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS"
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL"
export const PATIENT_LIST_RESET = "PATIENT_LIST_RESET"