export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST"
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS"
export const OTP_VERIFY_FAIL = "OTP_VERIFY_FAIL"

export const FORGOT_PWD_REQUEST = "FORGOT_PWD_REQUEST"
export const FORGOT_PWD_SUCCESS = "FORGOT_PWD_SUCCESS"
export const FORGOT_PWD_FAIL = "FORGOT_PWD_FAIL"

export const RESET_PWD_REQUEST = "RESET_PWD_REQUEST"
export const RESET_PWD_SUCCESS = "RESET_PWD_SUCCESS"
export const RESET_PWD_FAIL = "RESET_PWD_FAIL"


export const CHANGE_PWD_REQUEST = "CHANGE_PWD_REQUEST"
export const CHANGE_PWD_SUCCESS = "CHANGE_PWD_SUCCESS"
export const CHANGE_PWD_FAIL = "CHANGE_PWD_FAIL"